//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BatchEncoder.rc
//
#define IDC_BUTTON_LOAD_CONFIG          101
#define IDC_BUTTON_SAVE_CONFIG          102
#define IDC_BUTTON_DEFAULT_CONFIG       103
#define IDD_BATCHENCODER_DIALOG         104
#define IDR_MAINFRAME                   105
#define IDR_MENU_MAIN                   106
#define IDD_DIALOG_PRESETS              108
#define IDD_DIALOG_FORMATS              109
#define IDD_DIALOG_ABOUT                110
#define IDD_DIALOG_ADVANCED             112
#define IDR_ACCELERATOR_BATCHENCODER    114
#define IDR_MENU_TRAY                   115
#define IDR_PRESET_AAC_FAAC             116
#define IDR_PRESET_APE_MAC              117
#define IDR_PRESET_FLAC_FLAC            118
#define IDR_PRESET_M4A_FAAC             119
#define IDR_PRESET_MP3_LAME             120
#define IDR_PRESET_MP4_FAAC             121
#define IDR_PRESET_MPC_MPCENC           122
#define IDR_PRESET_OGG_OGGENC           123
#define IDR_PRESET_WV_WAVPACK           124
#define IDR_CONFIG_BATCHENCODER         125
#define IDR_PRESET_TTA_TTAENC           126
#define IDR_PRESET_OFR_OFR              127
#define IDR_PRESET_WAV_SSRC             128
#define IDR_MENU_STAT                   129
#define IDI_ICON_PROGRESS_01            130
#define IDI_ICON_PROGRESS_02            131
#define IDI_ICON_PROGRESS_03            132
#define IDI_ICON_PROGRESS_04            133
#define IDI_ICON_PROGRESS_05            134
#define IDI_ICON_PROGRESS_06            135
#define IDI_ICON_PROGRESS_07            136
#define IDI_ICON_PROGRESS_08            137
#define IDI_ICON_PROGRESS_09            138
#define IDI_ICON_PROGRESS_10            139
#define IDI_ICON_PROGRESS_11            140
#define IDI_ICON_PROGRESS_12            141
#define IDR_PRESET_MP4_NERO             142
#define IDR_PRESET_M4A_NERO             143
#define IDR_PRESET_TAK_TAKC             144
#define IDR_PRESET_AC3_AFTEN            145
#define IDC_BUTTON_RUN                  1001
#define IDC_PROGRESS_WORK               1002
#define IDC_COMBO_PRESETS               1003
#define IDC_COMBO_FORMAT                1004
#define IDC_EDIT_OUT_PATH               1005
#define IDC_BUTTON_BROWSE_PATH          1006
#define IDC_CHECK_OUT_PATH              1007
#define IDC_EDIT_INPUT_ITEMS            1008
#define IDC_EDIT_PD_PRESETS             1009
#define IDC_BUTTON_PD_SAVE_PRESETS      1010
#define IDC_BUTTON_PD_LOAD_PRESETS      1011
#define IDC_BUTTON_PD_REMOVE_PRESETS    1012
#define IDC_BUTTON_PD_REMOVE_ALL_PRESETS 1013
#define IDC_EDIT_PD_OPTIONS             1014
#define IDC_BUTTON_PD_UPDATE_PRESET     1015
#define IDC_BUTTON_PD_ADD_PRESET        1016
#define IDC_EDIT_FD_CLI_PATH            1017
#define IDC_EDIT_PD_NAME                1018
#define IDC_EDIT_FD_CLI_TEMPLATE        1019
#define IDC_BUTTON_FD_BROWSE            1020
#define IDC_BUTTON_PD_UP                1021
#define IDC_EDIT_FD_CLI_PROGRESS        1022
#define IDC_BUTTON_PD_DOWN              1023
#define IDC_BUTTON_FD_BROWSE_PROGRESS   1024
#define IDC_BUTTON_PD_UPDATE            1025
#define IDC_STATIC_TEXT_APP_NAME        1026
#define IDC_COMBO_PD_FORMAT             1027
#define IDC_EDIT_PD_PATH_TO_CONFIG      1028
#define IDC_STATIC_TEXT_WEBSITE         1030
#define IDC_STATIC_TEXT_EMAIL           1032
#define IDC_STATIC_GROUP_OUTPUT         1035
#define IDC_STATIC_TEXT_PRESET          1036
#define IDC_STATIC_TEXT_FORMAT          1037
#define IDC_STATIC_PD_TEXT_NAME         1038
#define IDC_STATIC_PD_TEXT_OPTIONS      1039
#define IDC_COMBO_PRIORITY_THREAD       1040
#define IDC_COMBO_PRIORITY_PROCESS      1041
#define IDC_CHECK_OPTION_DELETE         1042
#define IDC_CHECK_OPTION_ERROR          1043
#define IDC_EDIT_CONSOLE_LOG_FILE       1044
#define IDC_BUTTON_BROWSE_LOG           1045
#define IDC_RADIO_ENCODING_ANSI         1046
#define IDC_RADIO_ENCODING_UNICODE      1047
#define IDC_RADIO_ENCODING_UTF8         1048
#define IDC_CHECK_FD_PIPES_INPUT        1049
#define IDC_EDIT_FD_FORMATS             1050
#define IDC_CHECK_FD_PIPES_OUTPUT       1051
#define IDC_BUTTON_FD_UPDATE_PRESET     1052
#define IDC_STATIC_FD_TEXT_PATH         1053
#define IDC_STATIC_LICENSE              1054
#define IDC_STATIC_FD_TEXT_TEMPLATE     1055
#define IDC_STATIC_FD_TEXT_PROGRESS     1056
#define IDC_STATIC_GROUP_FD_PIPES       1057
#define ID_HELP_ABOUT                   32771
#define ID_FILE_EXIT                    32772
#define ID_HELP_WEBSITE                 32774
#define ID_EDIT_ADDDIR                  32775
#define ID_EDIT_OPEN                    32778
#define ID_EDIT_EXPLORE                 32779
#define ID_EDIT_REMOVE                  32780
#define ID_EDIT_CROP                    32781
#define ID_EDIT_RENAME                  32782
#define ID_EDIT_CHECKSELECTED           32783
#define ID_EDIT_UNCHECKSELECTED         32784
#define ID_EDIT_ADDFILES                32785
#define ID_OPTIONS_STAYONTOP            32786
#define ID_OPTIONS_DELETESOURCEFILEWHENDONE 32787
#define ID_OPTIONS_LOGCONSOLEOUTPUT     32788
#define ID_OPTIONS_SHOWLOGLIST          32789
#define ID_EDIT_RESETOUTPUT             32790
#define ID_OPTIONS_ADVANCED             32791
#define ID_OPTIONS_DO_NOT_SAVE          32792
#define ID_EDIT_RESETTIME               32793
#define ID_EDIT_SELECTALL               32794
#define ID_FILE_LOADLIST                32795
#define ID_FILE_SAVELIST                32796
#define ID_OPTIONS_CONFIGUREPRESETS     32797
#define ID_OPTIONS_CONFIGUREFORMAT      32798
#define ID_FILE_CLEARLIST               32799
#define ID_ACTION_CONVERT               32800
#define ID_OPTIONS_SHOWTRAYICON         32801
#define ID_EDIT_SELECTNONE              32802
#define ID_EDIT_INVERTSELECTION         32803
#define ID_ACCELERATOR_CTRL_S           32804
#define ID_ACCELERATOR_CTRL_L           32805
#define ID_ACCELERATOR_CTRL_E           32806
#define ID_ACCELERATOR_F3               32807
#define ID_ACCELERATOR_F4               32808
#define ID_ACCELERATOR_F5               32809
#define ID_ACCELERATOR_F6               32810
#define ID_ACCELERATOR_F2               32811
#define ID_ACCELERATOR_CTRL_A           32812
#define ID_ACCELERATOR_CTRL_N           32813
#define ID_ACCELERATOR_CTRL_I           32814
#define ID_ACCELERATOR_CTRL_O           32815
#define ID_ACCELERATOR_CTRL_D           32816
#define ID_ACCELERATOR_F9               32817
#define ID_ACCELERATOR_F10              32818
#define ID_ACCELERATOR_F7               32819
#define ID_ACCELERATOR_F8               32820
#define ID_ACCELERATOR_CTRL_SHIFT_A     32821
#define ID_TRAYMENU_EXIT                32823
#define ID_VIEW_SHOWGRIDLINES           32824
#define ID_OPTIONS_SHUTDOWN_WHEN_FINISHED 32825
#define ID_ACCELERATOR_CTRL_Q           32826
#define ID_ACCELERATOR_ALT_F4           32827
#define ID_ACCELERATOR_CTRL_SHIFT_L     32828
#define ID_ACCELERATOR_CTRL_SHIFT_S     32829
#define ID_ACCELERATOR_CTRL_PLUS        32830
#define ID_ACCELERATOR_CTRL_MINUS       32831
#define ID_ACCELERATOR_SHIFT_PLUS       32832
#define ID_ACCELERATOR_SHIFT_MINUS      32833
#define ID_ACCELERATOR_CTRL_G           32834
#define ID_ACCELERATOR_CTRL_SHIFT_D     32835
#define ID_ACCELERATOR_F12              32836
#define ID_ACCELERATOR_CTRL_F12         32837
#define ID_ACCELERATOR_CTRL_SHIFT_O     32838
#define ID_ACCELERATOR_F11              32839
#define ID_ACCELERATOR_CTRL_X           32840
#define ID_STATUSMENU_RESETCONVERSIONSTATUS 32841
#define ID_OPTIONS_DELETELOG            32845
#define ID_ACCELERATOR_SHIFT_F12        32846
#define ID_EDIT_REMOVECHECKED           32851
#define ID_EDIT_REMOVEUNCHECKED         32852
#define ID_OPTIONS_FORCECONSOLEWINDOW   32853
#define ID_ACCELERATOR_CTRL_SHIFT_F     32854
#define ID_FILE_CREATE_BATCH_FILE       32855
#define ID_ACCELERATOR_CTRL_B           32856
#define ID_OPTIONS_CONFIGUREEXTENSIONS  32857

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
