//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BatchEncoder.rc
//
#define IDI_ICON_MAIN                   101
#define IDD_DIALOG_MAIN                 102
#define IDD_DIALOG_PRESETS              103
#define IDD_DIALOG_FORMATS              104
#define IDD_DIALOG_ABOUT                105
#define IDR_MENU_MAIN                   106
#define IDR_ACCELERATOR_MAIN            107
#define IDC_LIST_ITEMS                  1001
#define IDC_STATIC_GROUP_OUTPUT         1002
#define IDC_STATIC_TEXT_FORMAT          1003
#define IDC_COMBO_FORMAT                1004
#define IDC_STATIC_TEXT_PRESET          1005
#define IDC_COMBO_PRESETS               1006
#define IDC_CHECK_OUTPUT                1007
#define IDC_EDIT_OUTPUT                 1008
#define IDC_BUTTON_BROWSE_OUTPUT        1009
#define IDC_STATIC_THREAD_COUNT         1010
#define IDC_EDIT_THREADCOUNT            1011
#define IDC_SPIN_THREADCOUNT            1012
#define IDC_BUTTON_CONVERT              1013
#define IDC_PROGRESS_CONVERT            1014
#define IDC_COMBO_PRESET_FORMAT         1020
#define IDC_LIST_PRESETS                1021
#define IDC_STATIC_PRESET_NAME          1022
#define IDC_EDIT_PRESET_NAME            1023
#define IDC_STATIC_PRESET_OPTIONS       1024
#define IDC_EDIT_PRESET_OPTIONS         1025
#define IDC_BUTTON_PRESET_UP            1026
#define IDC_BUTTON_PRESET_DOWN          1027
#define IDC_BUTTON_PRESET_REMOVE_ALL    1028
#define IDC_BUTTON_PRESET_REMOVE        1029
#define IDC_BUTTON_PRESET_ADD           1030
#define IDC_BUTTON_PRESET_LOAD          1031
#define IDC_BUTTON_PRESET_SAVE          1032
#define IDC_BUTTON_PRESET_UPDATE        1033
#define IDC_LIST_FORMATS                1040
#define IDC_RADIO_TYPE_ENCODER          1041
#define IDC_RADIO_TYPE_DECODER          1042
#define IDC_STATIC_GROUP_FORMAT_TYPE    1043
#define IDC_CHECK_FORMAT_PIPES_INPUT    1044
#define IDC_CHECK_FORMAT_PIPES_OUTPUT   1045
#define IDC_STATIC_GROUP_FORMAT_PIPES   1046
#define IDC_STATIC_FORMAT_ID            1047
#define IDC_EDIT_FORMAT_ID              1048
#define IDC_STATIC_FORMAT_NAME          1049
#define IDC_EDIT_FORMAT_NAME            1050
#define IDC_STATIC_FORMAT_EXTENSION     1051
#define IDC_EDIT_FORMAT_EXTENSION       1052
#define IDC_STATIC_FORMAT_FORMATS       1053
#define IDC_EDIT_FORMAT_FORMATS         1054
#define IDC_STATIC_FORMAT_DEFAULT       1055
#define IDC_COMBO_FORMAT_DEFAULT        1056
#define IDC_STATIC_FORMAT_PATH          1057
#define IDC_BUTTON_BROWSE_PATH          1058
#define IDC_EDIT_FORMAT_PATH            1059
#define IDC_STATIC_FORMAT_TEMPLATE      1060
#define IDC_EDIT_FORMAT_TEMPLATE        1061
#define IDC_STATIC_FORMAT_FUNCTION      1062
#define IDC_EDIT_FORMAT_FUNCTION        1063
#define IDC_BUTTON_BROWSE_FUNCTION      1064
#define IDC_BUTTON_FORMAT_UP            1065
#define IDC_BUTTON_FORMAT_DOWN          1066
#define IDC_BUTTON_FORMAT_REMOVE_ALL    1067
#define IDC_BUTTON_FORMAT_REMOVE        1068
#define IDC_BUTTON_FORMAT_ADD           1069
#define IDC_BUTTON_FORMAT_LOAD          1070
#define IDC_BUTTON_FORMAT_SAVE          1071
#define IDC_BUTTON_FORMAT_UPDATE        1072
#define IDC_BUTTON_EDIT_PRESETS         1073
#define IDC_STATIC_FORMAT_CODE          1074
#define IDC_EDIT_FORMAT_CODE            1075
#define IDC_BUTTON_FORMAT_IMPORT        1076
#define IDC_BUTTON_FORMAT_EXPORT        1077
#define IDC_BUTTON_FORMAT_DUPLICATE     1078
#define IDC_STATIC_TEXT_APP_NAME        1080
#define IDC_STATIC_TEXT_WEBSITE         1081
#define IDC_STATIC_TEXT_EMAIL           1082
#define IDC_STATIC_LICENSE              1083
#define ID_FILE_LOADLIST                32771
#define ID_FILE_SAVELIST                32772
#define ID_FILE_CLEARLIST               32773
#define ID_FILE_EXIT                    32774
#define ID_EDIT_ADDFILES                32780
#define ID_EDIT_ADDDIR                  32781
#define ID_EDIT_RENAME                  32782
#define ID_EDIT_RESETTIME               32783
#define ID_EDIT_RESETOUTPUT             32784
#define ID_EDIT_REMOVE                  32785
#define ID_EDIT_CROP                    32786
#define ID_EDIT_REMOVECHECKED           32787
#define ID_EDIT_REMOVEUNCHECKED         32788
#define ID_EDIT_CHECKSELECTED           32789
#define ID_EDIT_UNCHECKSELECTED         32790
#define ID_EDIT_SELECTALL               32791
#define ID_EDIT_SELECTNONE              32792
#define ID_EDIT_INVERTSELECTION         32793
#define ID_EDIT_OPEN                    32794
#define ID_EDIT_EXPLORE                 32795
#define ID_ACTION_CONVERT               32800
#define ID_OPTIONS_CONFIGUREPRESETS     32810
#define ID_OPTIONS_CONFIGUREFORMAT      32811
#define ID_OPTIONS_DELETE_SOURCE        32812
#define ID_OPTIONS_SHUTDOWN_WINDOWS     32813
#define ID_OPTIONS_DO_NOT_SAVE          32814
#define ID_OPTIONS_DELETE_ON_ERRORS     32815
#define ID_OPTIONS_STOP_ON_ERRORS       32816
#define ID_OPTIONS_HIDE_CONSOLE         32817
#define ID_HELP_ABOUT                   32820
#define ID_HELP_WEBSITE                 32821
#define ID_ACCELERATOR_F5               32840
#define ID_ACCELERATOR_F6               32841
#define ID_ACCELERATOR_CTRL_L           32842
#define ID_ACCELERATOR_CTRL_S           32843
#define ID_ACCELERATOR_CTRL_E           32844
#define ID_ACCELERATOR_ALT_F4           32845
#define ID_ACCELERATOR_F2               32846
#define ID_ACCELERATOR_F3               32847
#define ID_ACCELERATOR_F4               32848
#define ID_ACCELERATOR_CTRL_PLUS        32849
#define ID_ACCELERATOR_CTRL_MINUS       32850
#define ID_ACCELERATOR_SHIFT_PLUS       32851
#define ID_ACCELERATOR_SHIFT_MINUS      32852
#define ID_ACCELERATOR_CTRL_A           32853
#define ID_ACCELERATOR_CTRL_N           32854
#define ID_ACCELERATOR_CTRL_I           32855
#define ID_ACCELERATOR_F9               32856
#define ID_ACCELERATOR_F7               32857
#define ID_ACCELERATOR_F8               32858
#define ID_LANGUAGE_DEFAULT             32860

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         32870
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
