//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BatchEncoder.rc
//

#define IDR_MAINFRAME                   101
#define IDD_BATCHENCODER_DIALOG         102
#define IDD_DIALOG_PRESETS              103
#define IDD_DIALOG_FORMATS              104
#define IDD_DIALOG_ABOUT                105
#define IDD_DIALOG_ADVANCED             106
#define IDR_MENU_MAIN                   107
#define IDR_MENU_TRAY                   108
#define IDR_MENU_STAT                   109
#define IDR_ACCELERATOR_BATCHENCODER    110
#define IDI_ICON_PROGRESS_01            111
#define IDI_ICON_PROGRESS_02            112
#define IDI_ICON_PROGRESS_03            113
#define IDI_ICON_PROGRESS_04            114
#define IDI_ICON_PROGRESS_05            115
#define IDI_ICON_PROGRESS_06            116
#define IDI_ICON_PROGRESS_07            117
#define IDI_ICON_PROGRESS_08            118
#define IDI_ICON_PROGRESS_09            119
#define IDI_ICON_PROGRESS_10            120
#define IDI_ICON_PROGRESS_11            121
#define IDI_ICON_PROGRESS_12            122
#define IDC_BUTTON_LOAD_CONFIG          1001
#define IDC_BUTTON_SAVE_CONFIG          1002
#define IDC_BUTTON_RUN                  1004
#define IDC_PROGRESS_WORK               1005
#define IDC_COMBO_PRESETS               1006
#define IDC_COMBO_FORMAT                1007
#define IDC_EDIT_OUT_PATH               1008
#define IDC_BUTTON_BROWSE_PATH          1009
#define IDC_CHECK_OUT_PATH              1010
#define IDC_EDIT_INPUT_ITEMS            1011
#define IDC_EDIT_PD_PRESETS             1012
#define IDC_BUTTON_PD_SAVE_PRESETS      1013
#define IDC_BUTTON_PD_LOAD_PRESETS      1014
#define IDC_BUTTON_PD_REMOVE_PRESETS    1015
#define IDC_BUTTON_PD_REMOVE_ALL_PRESETS 1016
#define IDC_EDIT_PD_OPTIONS             1017
#define IDC_BUTTON_PD_UPDATE_PRESET     1018
#define IDC_BUTTON_PD_ADD_PRESET        1019
#define IDC_EDIT_FD_CLI_PATH            1020
#define IDC_EDIT_PD_NAME                1021
#define IDC_EDIT_FD_CLI_TEMPLATE        1022
#define IDC_BUTTON_FD_BROWSE            1023
#define IDC_BUTTON_PD_UP                1024
#define IDC_EDIT_FD_CLI_PROGRESS        1025
#define IDC_BUTTON_PD_DOWN              1026
#define IDC_BUTTON_FD_BROWSE_PROGRESS   1027
#define IDC_BUTTON_PD_UPDATE            1028
#define IDC_STATIC_TEXT_APP_NAME        1029
#define IDC_COMBO_PD_FORMAT             1030
#define IDC_EDIT_PD_PATH_TO_CONFIG      1031
#define IDC_STATIC_TEXT_WEBSITE         1032
#define IDC_STATIC_TEXT_EMAIL           1033
#define IDC_STATIC_GROUP_OUTPUT         1034
#define IDC_STATIC_TEXT_PRESET          1035
#define IDC_STATIC_TEXT_FORMAT          1036
#define IDC_STATIC_PD_TEXT_NAME         1037
#define IDC_STATIC_PD_TEXT_OPTIONS      1038
#define IDC_CHECK_OPTION_DELETE         1041
#define IDC_CHECK_OPTION_ERROR          1042
#define IDC_EDIT_CONSOLE_LOG_FILE       1043
#define IDC_BUTTON_BROWSE_LOG           1044
#define IDC_RADIO_ENCODING_ANSI         1045
#define IDC_RADIO_ENCODING_UNICODE      1046
#define IDC_RADIO_ENCODING_UTF8         1047
#define IDC_CHECK_FD_PIPES_INPUT        1048
#define IDC_EDIT_FD_FORMATS             1049
#define IDC_CHECK_FD_PIPES_OUTPUT       1050
#define IDC_BUTTON_FD_UPDATE_PRESET     1051
#define IDC_STATIC_FD_TEXT_PATH         1052
#define IDC_STATIC_LICENSE              1053
#define IDC_STATIC_FD_TEXT_TEMPLATE     1054
#define IDC_STATIC_FD_TEXT_PROGRESS     1055
#define IDC_STATIC_GROUP_FD_PIPES       1056
#define ID_HELP_ABOUT                   32771
#define ID_FILE_EXIT                    32772
#define ID_HELP_WEBSITE                 32773
#define ID_EDIT_ADDDIR                  32774
#define ID_EDIT_OPEN                    32775
#define ID_EDIT_EXPLORE                 32776
#define ID_EDIT_REMOVE                  32777
#define ID_EDIT_CROP                    32778
#define ID_EDIT_RENAME                  32779
#define ID_EDIT_CHECKSELECTED           32780
#define ID_EDIT_UNCHECKSELECTED         32781
#define ID_EDIT_ADDFILES                32782
#define ID_OPTIONS_STAYONTOP            32783
#define ID_OPTIONS_DELETESOURCEFILEWHENDONE 32784
#define ID_OPTIONS_LOGCONSOLEOUTPUT     32785
#define ID_OPTIONS_SHOWLOGLIST          32786
#define ID_EDIT_RESETOUTPUT             32787
#define ID_OPTIONS_ADVANCED             32788
#define ID_OPTIONS_DO_NOT_SAVE          32789
#define ID_EDIT_RESETTIME               32790
#define ID_EDIT_SELECTALL               32791
#define ID_FILE_LOADLIST                32792
#define ID_FILE_SAVELIST                32793
#define ID_OPTIONS_CONFIGUREPRESETS     32794
#define ID_OPTIONS_CONFIGUREFORMAT      32795
#define ID_FILE_CLEARLIST               32796
#define ID_ACTION_CONVERT               32797
#define ID_OPTIONS_SHOWTRAYICON         32798
#define ID_EDIT_SELECTNONE              32799
#define ID_EDIT_INVERTSELECTION         32800
#define ID_ACCELERATOR_CTRL_S           32801
#define ID_ACCELERATOR_CTRL_L           32802
#define ID_ACCELERATOR_CTRL_E           32803
#define ID_ACCELERATOR_F3               32804
#define ID_ACCELERATOR_F4               32805
#define ID_ACCELERATOR_F5               32806
#define ID_ACCELERATOR_F6               32807
#define ID_ACCELERATOR_F2               32808
#define ID_ACCELERATOR_CTRL_A           32809
#define ID_ACCELERATOR_CTRL_N           32810
#define ID_ACCELERATOR_CTRL_I           32811
#define ID_ACCELERATOR_CTRL_O           32812
#define ID_ACCELERATOR_CTRL_D           32813
#define ID_ACCELERATOR_F9               32814
#define ID_ACCELERATOR_F10              32815
#define ID_ACCELERATOR_F7               32816
#define ID_ACCELERATOR_F8               32817
#define ID_ACCELERATOR_CTRL_SHIFT_A     32818
#define ID_TRAYMENU_EXIT                32819
#define ID_VIEW_SHOWGRIDLINES           32820
#define ID_OPTIONS_SHUTDOWN_WHEN_FINISHED 32821
#define ID_ACCELERATOR_CTRL_Q           32822
#define ID_ACCELERATOR_ALT_F4           32823
#define ID_ACCELERATOR_CTRL_SHIFT_L     32824
#define ID_ACCELERATOR_CTRL_SHIFT_S     32825
#define ID_ACCELERATOR_CTRL_PLUS        32826
#define ID_ACCELERATOR_CTRL_MINUS       32827
#define ID_ACCELERATOR_SHIFT_PLUS       32828
#define ID_ACCELERATOR_SHIFT_MINUS      32829
#define ID_ACCELERATOR_CTRL_G           32830
#define ID_ACCELERATOR_F12              32832
#define ID_ACCELERATOR_CTRL_F12         32833
#define ID_ACCELERATOR_CTRL_SHIFT_O     32834
#define ID_ACCELERATOR_F11              32835
#define ID_ACCELERATOR_CTRL_X           32836
#define ID_STATUSMENU_RESETCONVERSIONSTATUS 32837
#define ID_OPTIONS_DELETELOG            32838
#define ID_ACCELERATOR_SHIFT_F12        32839
#define ID_EDIT_REMOVECHECKED           32840
#define ID_EDIT_REMOVEUNCHECKED         32841
#define ID_OPTIONS_FORCECONSOLEWINDOW   32842
#define ID_ACCELERATOR_CTRL_SHIFT_F     32843
#define ID_OPTIONS_CONFIGUREEXTENSIONS  32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
